# Generated by Django 6.0.5 on 2026-05-05 17:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grupo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=1)),
                ('descricao', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nome_guerra', models.CharField(max_length=50)),
                ('posicao', models.CharField(choices=[('goleiro', 'Goleiro'), ('zagueiro', 'Zagueiro'), ('lateral', 'Lateral'), ('volante', 'Volante'), ('meia', 'Meia'), ('atacante', 'Atacante')])),
                ('numero_camisa', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(26)])),
                ('data_nascimento', models.DateField()),
                ('suspenso', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Jogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('grupos', 'Grupos'), ('fase32', 'Fase32'), ('oitavas', 'Oitavas'), ('quartas', 'QUARTAS'), ('semifinal', 'Semifinal'), ('final', 'Final')])),
                ('data_hora', models.DateTimeField()),
                ('estadio', models.CharField(blank=True, max_length=150)),
                ('cidade', models.CharField(blank=True, max_length=100)),
                ('gols_mandante', models.PositiveSmallIntegerField(default=0)),
                ('gols_visitante', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('agendado', 'Agendado'), ('em_andamento', 'Em_andamento'), ('encerrado', 'Encerrado'), ('cancelado', 'Cancelado')])),
                ('grupo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='copa26.grupo')),
            ],
        ),
        migrations.CreateModel(
            name='EventoJogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('gol', 'Gol'), ('cartao_amarelo', 'Cartao_amarelo'), ('cartao_vermelho', 'Cartao_vermelho'), ('gol_contra', 'Gol_contra')])),
                ('minuto', models.PositiveSmallIntegerField()),
                ('acrescimo', models.BooleanField(default=False)),
                ('jogador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos', to='copa26.jogador')),
                ('jogo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='copa26.jogo')),
            ],
        ),
        migrations.CreateModel(
            name='Selecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=3, unique=True)),
                ('confederacao', models.CharField(choices=[('uefa', 'UEFA'), ('conmebol', 'Conmebol'), ('concacaf', 'Concacaf'), ('afc', 'Afc'), ('caf', 'Caf'), ('ofc', 'Ofc')])),
                ('escudo_url', models.URLField(blank=True)),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selecoes', to='copa26.grupo')),
                ('tecnico', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecao', to='copa26.tecnico')),
            ],
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_mandante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos_mandante', to='copa26.selecao'),
        ),
        migrations.AddField(
            model_name='jogo',
            name='selecao_visitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogos_visitante', to='copa26.selecao'),
        ),
        migrations.AddField(
            model_name='jogador',
            name='selecao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jogadores', to='copa26.selecao'),
        ),
    ]
