# Generated by Django 6.0.5 on 2026-05-06 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copa26', '0002_alter_eventojogo_id_alter_grupo_id_alter_jogador_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventojogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jogador',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='jogo',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='confederacao',
            field=models.CharField(choices=[('uefa', 'UEFA'), ('conmebol', 'Conmebol'), ('concacaf', 'Concacaf'), ('afc', 'AFC'), ('caf', 'CAF'), ('ofc', 'OFC')]),
        ),
        migrations.AlterField(
            model_name='selecao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tecnico',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
